apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-producer-api
  name: location-producer-api
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30008
  selector:
    service: location-producer-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-producer-api
  name: location-producer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-producer-api
  template:
    metadata:
      labels:
        service: location-producer-api
    spec:
      containers:
      - image: idajana/location_producer_api:latest
        name: location-producer-api
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_TOPIC
      restartPolicy: Always
